### PR TITLE
JSON Parser

### PR DESCRIPTION
**Pull request by juliojimenez**
Signed-off-by: Julio Jimenez <julio@julioj.com>

Fixes #

## Proposed Changes

  - JSON Parser
  - A few more tests
  - 40ants-ci Workflows

### CODE REVIEW

**Comment by juliojimenez** [comment]
@svetlyak40wt I followed the 40ants-ci README and upon loading the system I received these errors

```lisp
CL-USER> (ql:quickload :clickhouse-cl)
To load "clickhouse-cl":
  Load 1 ASDF system:
    clickhouse-cl
; Loading "clickhouse-cl"
[package clickhouse.ci]

; file: /home/julio/quicklisp/local-projects/clickhouse-cl/src/ci.lisp
; in: DEFWORKFLOW LINTER
;     ((40ANTS-CI/JOBS/LINTER:LINTER))
; 
; caught ERROR:
;   illegal function call

; in: DEFWORKFLOW CRITIC
;     ((40ANTS-CI/JOBS/CRITIC:CRITIC))
; 
; caught ERROR:
;   illegal function call

; in: DEFWORKFLOW D
;     ((40ANTS-CI/JOBS/DOCS:BUILD-DOCS))
; 
; caught ERROR:
;   illegal function call
```
If I do `C-c C-c` on `src/ci.lisp` it reports the `defworkflow linter|critic|docs` symbol as unbound. I've also tried changing their names in case of conflict.

I'm probably missing something totally obvious 🤣

**Comment by svetlyak40wt** [comment]
Trying to load clickhouse-cl from this branch, I'm getting this error:

```
The name "LEXER" does not designate any package.
   [Condition of type PACKAGE-DOES-NOT-EXIST]

Restarts:
 0: [CONTINUE] Use the current package, COMMON-LISP-USER.
 1: [RETRY] Retry finding the package.
 2: [USE-VALUE] Specify a different package
 3: [RETRY] Retry compiling #<CL-SOURCE-FILE "clickhouse-cl" "src" "ch-sql-parser">.
 4: [ACCEPT] Continue, treating compiling #<CL-SOURCE-FILE "clickhouse-cl" "src" "ch-sql-parser"> as having been successful.
 5: [RETRY] Retry ASDF operation.
 --more--

Backtrace:
 0: (SB-INT:%FIND-PACKAGE-OR-LOSE "LEXER")
 1: (SB-INT:FIND-UNDELETED-PACKAGE-OR-LOSE "LEXER")
 2: (SB-IMPL::USE-LIST-PACKAGES NIL ("CL" "LEXER"))
 3: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN SB-IMPL::%DEFPACKAGE))
 4: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
 5: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<FUNCTION (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN SB-IMPL::%DEFPACKAGE) {1088934EB}> #<SB-THREAD:MUTEX "Package Graph Lock" owner: #<SB-THREAD:THREAD "sly-..
 6: (SB-IMPL::%DEFPACKAGE "CLICKHOUSE.CH-SQL-PARSER" NIL NIL NIL NIL ("CL" "LEXER") NIL NIL ("MAKE-QUERY") ("CLICKHOUSE.CH-SQL-PARSER") NIL NIL #S(SB-C:DEFINITION-SOURCE-LOCATION :NAMESTRING "/Users/art/p..
 7: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SB-IMPL::%DEFPACKAGE "CLICKHOUSE.CH-SQL-PARSER" (QUOTE NIL) (QUOTE NIL) (QUOTE NIL) (QUOTE NIL) ...) #<NULL-LEXENV>)
 8: (SB-INT:SIMPLE-EVAL-IN-LEXENV (PROGN (SB-IMPL::%DEFPACKAGE "CLICKHOUSE.CH-SQL-PARSER" (QUOTE NIL) (QUOTE NIL) (QUOTE NIL) (QUOTE NIL) ...)) #<NULL-LEXENV>)
 9: (EVAL-TLF (PROGN (SB-IMPL::%DEFPACKAGE "CLICKHOUSE.CH-SQL-PARSER" (QUOTE NIL) (QUOTE NIL) (QUOTE NIL) (QUOTE NIL) ...)) 0 #<NULL-LEXENV>)
```

**Comment by svetlyak40wt** [comment]
I've fixed the problem with dependencies in this commit: https://github.com/juliojimenez/clickhouse-cl/pull/25/commits/7c7d1178fe81b9f2d98ca80e837c3bf8fd1a7ca1

For my own projects I prefer package-inferred asdf systems. ASDF figures out dependencies from the structure of packages and you don't need to specify "depends-on" for components in ASD file.

**Comment by svetlyak40wt** [comment]
Also, community does not like to have `cl-` prefix or `-cl` suffix in ASDF system names. It is obvious, that ASDF system is already for Common Lisp. So, project on github might have `-cl` suffix, but I suggest to rename ASDF system to `clickhouse.asd`.

**Comment by svetlyak40wt** [comment]
Please, wait a little, I'm trying to push fixed CI script :)

**Comment by juliojimenez** [comment]
I'll stop for now, thank you so much for your help Alexander!! 🙇

**Comment by svetlyak40wt** [comment]
I noticed that you have added a few asdf systems such as lexer, parser and re. If they are missing then it is better to add them to Quicklisp as separate projects.

**Comment by svetlyak40wt** [comment]
I can also help you to setup [40ants-doc](https://40ants.com/doc/) for making a beautiful documentation.

**Comment by juliojimenez** [comment]
> I noticed that you have added a few asdf systems such as lexer, parser and re. If they are missing then it is better to add them to Quicklisp as separate projects.

Those projects belong to https://github.com/massung, he has opted not add them to quicklisp, which is why I just brought them into the repo as-is. Not the most elegant thing to do I'm sure.

**Comment by svetlyak40wt** [comment]
Why @massung does not want to add these projects to Quicklisp? If he just didn't it because he don't care, then we can create an issue here https://github.com/quicklisp/quicklisp-projects ourselfs and ask to add these projects.

Also you can add them to Ultralisp and they will be included to the distribution right now.

**Comment by massung** [comment]
Hey all. Always neat to see code being used 😄! My reasoning on QuickLisp has just been two parts: 

1. I don't use QuickLisp. I'm not against it or anything, I just have never had a need to set it up and use it for anything. I use ASDF and just manage my own dependencies that way.
2. Because I don't use QuickLisp, I haven't had to concern myself with (library) name clashes. Multiple times in the past I've has issues and PRs posted asking me to rename my packages to something else because they conflict with other packages in QL. 

Until recently, I didn't want to go through the hassle of renaming, updating (my) code to resolve a conflict I never had to deal with myself.

That said, last summer I decided that while I still wasn't really up for adding stuff to QuickLisp myself, I thought I'd go through the pain of moving all the code to a common location and renaming all the packages to something consistent for everyone else who's been using them.

https://github.com/cl-boost/

I made the `cl-boost` org in GitHub and moved all my CL libraries there, each being renamed to `boost-xxx` (e.g. `boost-json` in this particular case).

My hope was that this would be a big initial step. 

As for QuickLisp, if someone wanted somehow add the `cl-boost` repositories to QL to make them more broadly accessible to the community, I certainly wouldn't be against it. And obviously the repos there are open and if people would like to contribute I do accepts PRs (I don't know what's involved in adding something to QL). 

Regardless, it's really great to see the code being used! Thanks!

**Comment by juliojimenez** [comment]
> Regardless, it's really great to see the code being used! Thanks!

Hey @massung Jeffrey! Your lexer library was just what I was looking for. I don't think my use does it justice, hopefully as time goes on we can get fancier with it. 😄 I will definitely checkout the boost-* collection. 🚀

**Comment by juliojimenez** [comment]
@svetlyak40wt Update: 😅  The critic and linter checks finally passed now that the overall system is less crappy 💩  For docs the output reported `System "40ants-doc/changelog" not found`. I tried this...

```lisp
(asdf:defsystem #:clickhouse/ci
  :description "CI for Common Lisp ClickHouse Client Library"

  :author "julio@clickhouse.com"
  :license  "Apache-2.0"
  :depends-on (#:40ants-ci
	       #:40ants-doc/changelog)
  :components ((:module "src"
		:components
		((:file "ci")))))
```

...but the same error was thrown, so I don't think I understood the exception correctly, what do you think?

**Comment by svetlyak40wt** [comment]
Add the primary ASDF system #:40ants-doc and then #:40ants-doc/changelog. Otherwise Quicklisp is not able to figure out what to download.

**Pull request merged**
