### PR TITLE
:infinity: Fix CI

### PR DESCRIPTION
**Pull request by juliojimenez**
Signed-off-by: Julio Jimenez <julio@julioj.com>

Fixes #

## Proposed Changes

  - Fix CI

### CODE REVIEW

**Comment by svetlyak40wt** [comment]
The problem is in this line:

```
:perform (test-op (o c) (symbol-call :fiveam '#:run! 'clickhouse-test::all-tests)))
```

of clickhouse-test.asd.

At them moment, when lisp loads the asd file, there is no clickhouse-test package yet. That is why reader complains the package is not found.

Try to replace `'clickhouse-test::all-tests` with `(find-symbol "ALL-TESTS" "CLICKHOUSE-TEST")`.

**Comment by juliojimenez** [comment]
> The problem is in this line:
> 
> ```
> :perform (test-op (o c) (symbol-call :fiveam '#:run! 'clickhouse-test::all-tests)))
> ```
> 
> of clickhouse-test.asd.
> 
> At them moment, when lisp loads the asd file, there is no clickhouse-test package yet. That is why reader complains the package is not found.
> 
> Try to replace `'clickhouse-test::all-tests` with `(find-symbol "ALL-TESTS" "CLICKHOUSE-TEST")`.

You must've commented on this around the same time I found it on StackOverflow 🤣 Thank you!

I'm still having the issue of `System "lexer" not found`, I am pretty horrible at Common Lisp systems and packaging 😮‍💨

**Comment by svetlyak40wt** [comment]
> I'm still having the issue of System "lexer" not found, I am pretty horrible at Common Lisp systems and packaging 😮‍💨

I see all checks are passing now. What is the problem with lexer?

**Comment by juliojimenez** [comment]
> I see all checks are passing now. What is the problem with lexer?

Locally the tests run smoothly, but the CI workflow fails.

Screenshot 2023-02-02 10 23 24

**Pull request merged**
